<a href="https://colab.research.google.com/github/vinaybondhugula-bot/Resume_project/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install PyPDF2

Collecting PyPDF2
  Downloading pypdf2-3.0.1-py3-none-any.whl.metadata (6.8 kB)
Downloading pypdf2-3.0.1-py3-none-any.whl (232 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 4.3 MB/s eta 0:00:00
Installing collected packages: PyPDF2
Successfully installed PyPDF2-3.0.1

In [2]:
import os
import PyPDF2
import pandas as pd

In [3]:
from google.colab import files
uploaded = files.upload()

Saving Vinay_B_Resume.pdf to Vinay_B_Resume.pdf
Saving Vinay_Bondhugula_QA_Engineer_Resume.pdf to Vinay_Bondhugula_QA_Engineer_Resume.pdf
Saving VishalBondugulaResume.pdf to VishalBondugulaResume.pdf
Saving Kalva Srikar_Resume.pdf to Kalva Srikar_Resume.pdf
Saving Kotturu Bhargav Teja_Resume (2).pdf to Kotturu Bhargav Teja_Resume (2).pdf
Saving Renikunta_Shiva Prasad_resume.pdf to Renikunta_Shiva Prasad_resume.pdf
Saving Venkatesh Goriparthi_SAP MM Consultant (1) (1).pdf to Venkatesh Goriparthi_SAP MM Consultant (1) (1).pdf
Saving surya_charan_Resume (1)(1).pdf to surya_charan_Resume (1)(1).pdf
Saving Shivam Sharma - SAP ARIBA Consultant - SAP Certified(1).pdf to Shivam Sharma - SAP ARIBA Consultant - SAP Certified(1).pdf

In [4]:
print(os.listdir())

['.config', 'Vinay_B_Resume.pdf', 'Kotturu Bhargav Teja_Resume (2).pdf', 'Venkatesh Goriparthi_SAP MM Consultant (1) (1).pdf', 'VishalBondugulaResume.pdf', 'Kalva Srikar_Resume.pdf', 'Vinay_Bondhugula_QA_Engineer_Resume.pdf', 'Renikunta_Shiva Prasad_resume.pdf', 'Shivam Sharma - SAP ARIBA Consultant - SAP Certified(1).pdf', 'surya_charan_Resume (1)(1).pdf', 'sample_data']

In [8]:
data = []
for file in os.listdir():
  if file.lower().endswith(".pdf"):
    print("Reading",file)

    with open(file, 'rb') as f:
      reader = PyPDF2.PdfReader(f)
      text = ""
      for page in reader.pages:
        if page.extract_text():
          text += page.extract_text()
    data.append({
        "file_name":file,
        "resume_text":text
    })

Reading Vinay_B_Resume.pdf
Reading Kotturu Bhargav Teja_Resume (2).pdf
Reading Venkatesh Goriparthi_SAP MM Consultant (1) (1).pdf
Reading VishalBondugulaResume.pdf
Reading Kalva Srikar_Resume.pdf
Reading Vinay_Bondhugula_QA_Engineer_Resume.pdf
Reading Renikunta_Shiva Prasad_resume.pdf
Reading Shivam Sharma - SAP ARIBA Consultant - SAP Certified(1).pdf
Reading surya_charan_Resume (1)(1).pdf

In [9]:
df = pd.DataFrame(data)
df.head()

,file_name,resume_text
0,Vinay_B_Resume.pdf,VINAY B\nSoftware Test Engineer | Python & Mac...
1,Kotturu Bhargav Teja_Resume (2).pdf,
2,Venkatesh Goriparthi_SAP MM Consultant (1) (1)...,Venkatesh Goriparthi \n \nSAP MM Consultant ...
3,VishalBondugulaResume.pdf,\nVishal Bondugula \nEmail: vishalbondugul...
4,Kalva Srikar_Resume.pdf,

In [13]:
skills_list = [
    "python", "sql", "java", "javascript", "react", "angular",
    "node", "django", "flask", "sap", "selenium", "cypress",
    "manual testing", "automation testing", "api testing",
    "aws", "azure", "docker", "kubernetes", ".net","jira","soql"
]

In [14]:
def extract_skills(text):
  found_skills = set()
  text = text.lower()
  for skill in skills_list:
      if skill in text:
          found_skills.add(skill)
  return ", ".join(found_skills)

In [15]:
df["skills"] = df["resume_text"].apply(extract_skills)
df.head()

,file_name,resume_text,skills
0,Vinay_B_Resume.pdf,VINAY B\nSoftware Test Engineer | Python & Mac...,"jira, api testing, python, manual testing"
1,Kotturu Bhargav Teja_Resume (2).pdf,,
2,Venkatesh Goriparthi_SAP MM Consultant (1) (1)...,Venkatesh Goriparthi \n \nSAP MM Consultant ...,"jira, sap"
3,VishalBondugulaResume.pdf,\nVishal Bondugula \nEmail: vishalbondugul...,".net, jira, sql"
4,Kalva Srikar_Resume.pdf,,

In [19]:
def extract_education(text):
    text = text.lower()

    if any(word in text for word in [
        "mtech", "m.tech", "mba", "master"
    ]):
        return "Masters"
    elif any(word in text for word in [
        "btech", "b.tech", "be", "b.e",
        "bsc", "b.sc", "bachelor","bachelor's"
    ]):
        return "Bachelors"

    else:
        return "Other"

In [20]:
df["education"] = df["resume_text"].apply(extract_education)
df.head()

,file_name,resume_text,skills,education
0,Vinay_B_Resume.pdf,VINAY B\nSoftware Test Engineer | Python & Mac...,"jira, api testing, python, manual testing",Bachelors
1,Kotturu Bhargav Teja_Resume (2).pdf,,,Other
2,Venkatesh Goriparthi_SAP MM Consultant (1) (1)...,Venkatesh Goriparthi \n \nSAP MM Consultant ...,"jira, sap",Masters
3,VishalBondugulaResume.pdf,\nVishal Bondugula \nEmail: vishalbondugul...,".net, jira, sql",Bachelors
4,Kalva Srikar_Resume.pdf,,,Other

In [21]:
df["skills_count"] = [len(x.split(","))if x else 0 for x in df["skills"]]
df.head()

,file_name,resume_text,skills,education,skills_count
0,Vinay_B_Resume.pdf,VINAY B\nSoftware Test Engineer | Python & Mac...,"jira, api testing, python, manual testing",Bachelors,4
1,Kotturu Bhargav Teja_Resume (2).pdf,,,Other,0
2,Venkatesh Goriparthi_SAP MM Consultant (1) (1)...,Venkatesh Goriparthi \n \nSAP MM Consultant ...,"jira, sap",Masters,2
3,VishalBondugulaResume.pdf,\nVishal Bondugula \nEmail: vishalbondugul...,".net, jira, sql",Bachelors,3
4,Kalva Srikar_Resume.pdf,,,Other,0

In [22]:
def extract_certification(text):
  text = text.lower()
  keywords = ["certification","certified","certifications"]
  return 1 if any(keyword in text for keyword in keywords) else 0

df["certification"] = df["resume_text"].apply(extract_certification)
df.head()

,file_name,resume_text,skills,education,skills_count,certification
0,Vinay_B_Resume.pdf,VINAY B\nSoftware Test Engineer | Python & Mac...,"jira, api testing, python, manual testing",Bachelors,4,0
1,Kotturu Bhargav Teja_Resume (2).pdf,,,Other,0,0
2,Venkatesh Goriparthi_SAP MM Consultant (1) (1)...,Venkatesh Goriparthi \n \nSAP MM Consultant ...,"jira, sap",Masters,2,0
3,VishalBondugulaResume.pdf,\nVishal Bondugula \nEmail: vishalbondugul...,".net, jira, sql",Bachelors,3,1
4,Kalva Srikar_Resume.pdf,,,Other,0,0

In [23]:
df = df[df["resume_text"].str.strip() != ""]

In [26]:
df.head()

,file_name,resume_text,skills,education,skills_count,certification
0,Vinay_B_Resume.pdf,VINAY B\nSoftware Test Engineer | Python & Mac...,"jira, api testing, python, manual testing",Bachelors,4,0
2,Venkatesh Goriparthi_SAP MM Consultant (1) (1)...,Venkatesh Goriparthi \n \nSAP MM Consultant ...,"jira, sap",Masters,2,0
3,VishalBondugulaResume.pdf,\nVishal Bondugula \nEmail: vishalbondugul...,".net, jira, sql",Bachelors,3,1
5,Vinay_Bondhugula_QA_Engineer_Resume.pdf,Summary\nDetail-oriented Quality Analyst with ...,"jira, api testing, python",Bachelors,3,0
6,Renikunta_Shiva Prasad_resume.pdf,Renikunta Shivaprasad\nrenikuntashivaprasad112...,"react, sql, java, javascript, python, django",Masters,6,0

In [39]:
def extract_projects(text):
  return text.lower().count("project")
df["project"] = df["resume_text"].apply(extract_projects)

In [40]:
df.head(3)

,file_name,resume_text,skills,education,skills_count,certification,experience,project
0,Vinay_B_Resume.pdf,VINAY B\nSoftware Test Engineer | Python & Mac...,"jira, api testing, python, manual testing",Bachelors,4,0,4.0,4
2,Venkatesh Goriparthi_SAP MM Consultant (1) (1)...,Venkatesh Goriparthi \n \nSAP MM Consultant ...,"jira, sap",Masters,2,0,4.0,2
3,VishalBondugulaResume.pdf,\nVishal Bondugula \nEmail: vishalbondugul...,".net, jira, sql",Bachelors,3,1,4.5,6

In [41]:
import re
def extract_experience(text):
    if not isinstance(text, str):
        return 0.0
    text = text.lower()
    text = re.sub(r'(\d)\s*\.\s*(\d)',r'\1.\2', text)
    matches = re.findall(r'(\d+(?:\.\d+)?)\+?\s*(years|year|yrs|yr)', text)

    for m in matches:
      val = float(m[0])
      if 0<val<20:
        return val
    return 0.0

In [42]:
df["experience"] = df["resume_text"].apply(extract_experience)
df.head(3)

,file_name,resume_text,skills,education,skills_count,certification,experience,project
0,Vinay_B_Resume.pdf,VINAY B\nSoftware Test Engineer | Python & Mac...,"jira, api testing, python, manual testing",Bachelors,4,0,4.0,4
2,Venkatesh Goriparthi_SAP MM Consultant (1) (1)...,Venkatesh Goriparthi \n \nSAP MM Consultant ...,"jira, sap",Masters,2,0,4.0,2
3,VishalBondugulaResume.pdf,\nVishal Bondugula \nEmail: vishalbondugul...,".net, jira, sql",Bachelors,3,1,4.5,6

In [43]:
df = df.rename(columns={"project":"project_count"})
df.head(3)

,file_name,resume_text,skills,education,skills_count,certification,experience,project_count
0,Vinay_B_Resume.pdf,VINAY B\nSoftware Test Engineer | Python & Mac...,"jira, api testing, python, manual testing",Bachelors,4,0,4.0,4
2,Venkatesh Goriparthi_SAP MM Consultant (1) (1)...,Venkatesh Goriparthi \n \nSAP MM Consultant ...,"jira, sap",Masters,2,0,4.0,2
3,VishalBondugulaResume.pdf,\nVishal Bondugula \nEmail: vishalbondugul...,".net, jira, sql",Bachelors,3,1,4.5,6

In [44]:
edu_map = {
    "Masters":2,
    "Bachelors":1,
    "Others":0
}
df["education_rank"] = df["education"].map(edu_map).fillna(0)

In [45]:
df.head(2)

,file_name,resume_text,skills,education,skills_count,certification,experience,project_count,education_rank
0,Vinay_B_Resume.pdf,VINAY B\nSoftware Test Engineer | Python & Mac...,"jira, api testing, python, manual testing",Bachelors,4,0,4.0,4,1
2,Venkatesh Goriparthi_SAP MM Consultant (1) (1)...,Venkatesh Goriparthi \n \nSAP MM Consultant ...,"jira, sap",Masters,2,0,4.0,2,2

In [47]:
y = df["experience"]
X= df.drop(columns=["file_name","resume_text","skills","education","experience"])

In [48]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [50]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [51]:
model.score(X_test,y_test)

-17.701883890811228

In [53]:
print(X.dtypes)

skills_count      int64
certification     int64
project_count     int64
education_rank    int64
dtype: object

In [57]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20],
    'min_samples_split':[2,5,10]
}

rf = RandomForestRegressor()
grid_search = GridSearchCV(estimator=rf, param_grid=param_grid, cv=5, scoring='r2')
grid_search.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

GridSearchCV(cv=5, estimator=RandomForestRegressor(),
             param_grid={'max_depth': [None, 10, 20],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [100, 200, 300]},
             scoring='r2')

In [58]:
len(X_train)

5

In [59]:
len(X_test)

2

In [60]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20],
    'min_samples_split':[2,5,10]
}

rf = RandomForestRegressor()
grid_search = GridSearchCV(estimator=rf, param_grid=param_grid, cv=2, scoring='r2')
grid_search.fit(X_train, y_train)

GridSearchCV(cv=2, estimator=RandomForestRegressor(),
             param_grid={'max_depth': [None, 10, 20],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [100, 200, 300]},
             scoring='r2')

In [61]:
print(grid_search.best_params_)

{'max_depth': None, 'min_samples_split': 2, 'n_estimators': 300}

In [62]:
y_pred = grid_search.predict(X_test)

In [63]:
print(y_pred)

[3.537 3.942]

In [64]:
final_score = grid_search.score(X_test,y_test)
print(final_score)

0.46690400000000665

In [65]:
results = pd.DataFrame({
    'Actual': y_test,
    'Predicted': y_pred
})
print(results)

   Actual  Predicted
7     3.0      3.537
3     4.5      3.942

In [66]:
importance = pd.Series(grid_search.best_estimator_.feature_importances_, index=X.columns)
print(importance.sort_values(ascending=False))

skills_count      0.576915
certification     0.226010
education_rank    0.111073
project_count     0.086002
dtype: float64

In [67]:
new_candidate_resume1 = [[6,1,2,3]]
score = grid_search.predict(new_candidate_resume1)
print(score)

[1.281]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

In [68]:
new_candidate_resume2 = [[4,0,1,1]]
score = grid_search.predict(new_candidate_resume2)
print(score)

[3.656]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

In [69]:
new_candidate_resume3 = [[1,0,1,0]]
score = grid_search.predict(new_candidate_resume3)
print(score)

[3.66466667]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

In [70]:
new_candidate_resume4 = [[1,0,0,0]]
score = grid_search.predict(new_candidate_resume4)
print(score)

[3.66466667]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

In [71]:
new_candidate_resume5 = [[15,1,2,3]]
score = grid_search.predict(new_candidate_resume4)
print(score)

[3.66466667]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(